# Generated by Django 4.0 on 2021-12-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sillystudents', '0003_course_lecture_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='data',
            new_name='date',
        ),
    ]
