# Generated by Django 4.0 on 2021-12-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sillystudents', '0007_rename_data_lecture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
